# Generated by Django 5.1.2 on 2024-11-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_rt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subwaystation',
            name='gtfs_stop_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
