# Generated by Django 5.1.2 on 2024-11-18 19:54

from django.db import migrations
import json

def load_subway_station_data(apps, schema_editor):
    SubwayStation = apps.get_model("gtfs_rt", "SubwayStation")
    with open('gtfs_rt/mta_subway_stations.geojson') as f:
        MTA_SUBWAY_STATIONS = json.load(f)
        
        for feature in MTA_SUBWAY_STATIONS['features']:
            station_info = feature['properties']
            SubwayStation.objects.create(
                                station_id = station_info['station_id'],
                                stop_name = station_info['stop_name'],
                                complex_id = station_info['complex_id'],
                                division = station_info['division'],
                                borough = station_info['borough'],
                                north_direction_label = station_info['north_direction_label'],
                                south_direction_label = station_info['south_direction_label'],
                                line = station_info['line'],
                                daytime_routes = station_info['daytime_routes'],
                                structure = station_info['structure'],
                                gtfs_stop_id = station_info['gtfs_stop_id'],
                                gtfs_latitude = station_info['gtfs_latitude'],
                                gtfs_longitude = station_info['gtfs_longitude'],
                                ada_notes = station_info['ada_notes'],
                                ada = station_info['ada'],
                                ada_northbound = station_info['ada_northbound'],
                                ada_southbound = station_info['ada_southbound'],
                                cbd = station_info['cbd'],
            )

class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_rt', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_subway_station_data, reverse_code=migrations.RunPython.noop),
    ]
    