# Generated by Django 5.1.2 on 2024-11-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_rt', '0003_subway_stations_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subwayentity',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subwayentity',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='subwaystation',
            name='gtfs_stop_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
