# Generated by Django 5.1.2 on 2024-12-10 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_rt', '0003_subway_stations_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subwayentity',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='subwayentity',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subwaystation',
            name='gtfs_stop_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='StopTimeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField(null=True)),
                ('departure_time', models.DateTimeField(null=True)),
                ('subway_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs_rt.subwayentity')),
            ],
            options={
                'unique_together': {('subway_entity', 'stop_id', 'arrival_time', 'departure_time')},
            },
        ),
    ]
