# Generated by Django 5.1.2 on 2024-11-26 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_rt', '0006_alter_subwaystoptimeupdate_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subwayentity',
            name='stop_time_updates',
        ),
        migrations.AddField(
            model_name='subwayentity',
            name='stop_time_updates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gtfs_rt.subwaystoptimeupdate'),
        ),
    ]
