# Generated by Django 5.1.2 on 2024-11-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_rt', '0007_remove_subwayentity_stop_time_updates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subwayentity',
            name='stop_time_updates',
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name='SubwayStopTimeUpdate',
        ),
    ]
